tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/php"
brew "autoconf"
brew "automake"
brew "readline"
brew "awscli"
brew "composer"
brew "convmv"
brew "git"
brew "lua"
brew "highlight"
brew "lha"
brew "memcached"
brew "libmemcached"
brew "mackup"
brew "mas"
brew "mysql"
brew "nodebrew"
brew "pkg-config"
brew "rbenv"
brew "ruby-build"
brew "s3cmd"
brew "tree"
brew "wget"
brew "yarn"
cask "amazon-music"
cask "atom"
cask "brackets"
cask "calibre"
cask "cheatsheet"
cask "cyberduck"
cask "dash"
cask "docker"
cask "fantastical"
cask "firefox"
cask "genymotion"
cask "github-desktop"
cask "google-chrome"
cask "google-chrome-canary"
cask "hyperswitch"
cask "imageoptim"
cask "istat-menus"
cask "kindle"
cask "lepton"
cask "linear"
cask "mamp"
cask "mapture"
cask "messenger"
cask "notion"
cask "omnifocus"
cask "paw"
cask "sequel-pro"
cask "sketch"
cask "skype"
cask "slack"
cask "spotify"
cask "sublime-text"
cask "transmit"
cask "vagrant"
cask "virtualbox"
cask "visual-studio-code"
cask "vlc"
mas "Airmail 3", id: 918858936
mas "AirSketch", id: 1286744480
mas "Be Focused", id: 973134470
mas "BetterSnapTool", id: 417375580
mas "CotEditor", id: 1024640650
mas "Gifted", id: 771955779
mas "iA Writer", id: 775737590
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Messages for Facebook", id: 604009912
mas "Momentum", id: 1030442215
mas "Monosnap", id: 540348655
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "PopClip", id: 445189367
mas "Proxy", id: 874920950
mas "Shotty", id: 1250306151
mas "The Unarchiver", id: 425424353
mas "Todoist", id: 585829637
mas "Tree 2", id: 944654199
mas "Twitter", id: 409789998
mas "WinArchiver Lite", id: 414855915
mas "Wunderlist", id: 410628904
