#!/bin/bash

# ------------------------------
# $ cat styles.css | csscount
# [Count number of selectors in a CSS file | alias.sh](http://alias.sh/count-number-selectors-css-file)
# ------------------------------

csscount() {
    cnt=0
    depth=0
    while read -n 1 char; do
            case $char in
                    "{")
                            ((depth++))
                            ;;
                    "}")
                            ((depth--))
                            if [ "$depth" -eq "0" ]; then
                                    ((cnt++))
                            fi
                            ;;
                    ",")
                            ((cnt++))
                            ;;
            esac
    done

    echo $cnt
}


# ------------------------------
# [gitで差分ファイルを抽出する - Qiita](http://qiita.com/kaminaly/items/28f9cb4e680deb700833)
# $ git_diff_archive 数値 : HEAD と HEAD~数値 の差分
# $ git_diff_archive コミット識別子 : HEAD と コミット識別子 の差分を抽出
# $ git_diff_archive コミット識別子1 コミット識別子2 : 2つのコミットの差分を抽出
# ------------------------------

function git_diff_archive() 
{
  local diff=""
  local h="HEAD"
  if [ $# -eq 1 ]; then
    if expr "$1" : '[0-9]*$' > /dev/null ; then
      diff="HEAD HEAD~${1}"
    else
      diff="HEAD ${1}"
    fi
  elif [ $# -eq 2 ]; then
    diff="${1} ${2}"
    h=$1
  fi
  if [ "$diff" != "" ]; then
    diff="git diff --diff-filter=D --name-only ${diff}"
  fi
  git archive --format=zip --prefix=root/ $h `eval $diff` -o archive.zip
}


